# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "ctf-box"
  config.vm.synced_folder "../ctf-shared", "/ctf-shared"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.cpus = 2 
     #the more cores and memory, the merrier.
  end
  
  #Setup Scripts
  config.vm.provision :shell, path: "scripts/provision-vagrant.sh"
  config.vm.provision :shell, path: "scripts/provision-vagrant-user.sh", privileged: false
end
