# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "jupyter-box"
  config.vm.network "forwarded_port", guest: 8888, host: 8888, host_ip: "127.0.0.1"
  config.vm.synced_folder "../ctf-shared", "/ctf-shared"

  config.vm.provider "vmware_desktop" do |vb|
     vb.memory = "2048"
     vb.cpus = 2 
     #the more cores and memory, the merrier.
  end
  
  #Setup Scripts
  config.vm.provision :shell, path: "scripts/provision-vagrant.sh"
  config.vm.provision :shell, path: "scripts/provision-vagrant-user.sh", privileged: false

  config.vm.provision :shell, path: "scripts/startup.sh", run: 'always'
  config.vm.post_up_message = "*****************************************\n\n" \
                              "    To access your Jupyter Notebook\n" \
                              "    point your browser to:\n\n" \
                              "        http://localhost:8888\n\n" \
                              "    Have fun!\n\n" \
                              "*****************************************"  
end
